### ISSUE TITLE
Dark theme issue

### ISSUE THREAD

**Issue by GinoHereIam** [michaldaniel/Ebook-Viewer#13]
Hi,

nice app :) 
here is a little issue with links:

![bildschirmfoto von 2016-10-18 19-55-37](https://cloud.githubusercontent.com/assets/3085830/19489794/f3cabbb4-956c-11e6-8572-24f3f30a6922.png)

**Comment by canweriotnow** [comment]
Running under xubuntu (xfce4) the Dark theme seems to just invert the text color without changing anything else:

![screenshot_2016-10-19_13-47-26](https://cloud.githubusercontent.com/assets/387693/19530965/f1ff6464-9603-11e6-9244-dbada58c1444.png)

**Comment by michaldaniel** [comment]
@GinoHereIam I'm pretty sure I know what causes that, but could you send the ebook file to my mail:  contact@michaldaniel.work so I can quickly confirm fix myself?

@canweriotnow This is another issue all together, it would be best to make separate thread and I'll need your system info: GTK version, and more info on xubuntu and xface version. I might not be able to fix it tho. I'm simply asking system to change app theme to GTK dark theme, I see you are even missing some icons.

Does the issue persist after restarting the app? Could you install `gtk-3-examples` and run `gtk3-wiget-factory` and see if you change in the settings there to "Dark theme" the app changes and looks fine?

**Comment by michaldaniel** [comment]
@GinoHereIam On another note, did you mess with icons or something in the source or in any other way? None of them seems correct but they look gnome default. This seems really strange.

**Comment by michaldaniel** [comment]
@GinoHereIam This shouldn't be an issue any more but I'll be doing big base.css work to do some styling of common epub selectors soon in order to fix similar possible formatting bugs.

**Comment by GinoHereIam** [comment]
Hi @michaldaniel, here is the link to the epub: [http://downloads.mysql.com/docs/connector-cpp-en.epub](http://downloads.mysql.com/docs/connector-cpp-en.epub). :)

**Comment by michaldaniel** [comment]
@GinoHereIam Your issue should be solved. I had to take break from development. I'm going to keep it open and investigate @canweriotnow reported problem.

**Comment by AnwarShah** [comment]
Same issue happens in MATE environment with Mint-X theme. The text's aren't readable at all in Light model

**Comment by dweymouth** [comment]
Can confirm the same issue is still present on Cinnamon desktop as well with default (Mint-X) theme.

**Comment by edbucks** [comment]
I set an appropriate theme for readable text via this environment variable on launch:

``GTK_THEME=Adwaita:light easy-ebook-viewer``

I hope this is helpful.
